# Generated by Django 3.1 on 2021-11-10 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_delete_prueba'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.IntegerField(unique=True)),
                ('cbu', models.IntegerField()),
                ('alias', models.CharField(max_length=100, unique=True)),
                ('banco_emisor', models.CharField(choices=[('nacion', 'Nacion'), ('santader', 'Santander'), ('galicia', 'Galicia')], max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='cuenta_bancaria',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.cuenta'),
        ),
    ]
