# Generated by Django 3.1 on 2021-11-10 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_auto_20211110_1944'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cuenta',
            new_name='CuentaBancaria',
        ),
    ]
