# Generated by Django 3.1 on 2021-11-10 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_auto_20211110_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadosalud',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='cuenta_bancaria',
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='persona',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.persona'),
        ),
    ]
