# Generated by Django 3.1 on 2021-11-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0006_auto_20211110_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentabancaria',
            name='banco_emisor',
            field=models.CharField(choices=[('nacion', 'Nacion'), ('santader', 'Santander'), ('galicia', 'Galicia')], max_length=100),
        ),
    ]
